# Generated by Django 2.0 on 2018-01-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=125)),
                ('post_title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=300)),
            ],
        ),
    ]
