# Generated by Django 2.0 on 2018-01-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_post_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
