# Generated by Django 2.0 on 2018-01-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20180108_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='poster_name',
        ),
    ]
